JOB_LIST = [
    "digital",
    "media",
    "executive",
    "tech",
    "operations",
    "technical",
    "support",
    "software",
    "engineer",
    "opening",
    "specialist",
    "consultant",
    "opportunity",
    "architect",
    "product",
    "assistant",
    "oracle",
    "manager",
    "marketing",
    "account",
    "developer",
    "job",
    "sales",
    "business",
    "development",
    "corporate",
    "java",
    "lead",
    "company",
    "web",
    "senior",
    "accounts",
    "system",
    "android",
    "international",
    "voice",
    "process",
    "shift",
    "head",
    "content",
    "data",
    "analyst",
    "associate",
    "design",
    "writer",
    "accounting",
    "php",
    "maintenance",
    "manager",
    "principal",
    "designer",
    "office",
    "project",
    "automation",
    "medical",
    "requirement",
    "management",
    "customer",
    "service",
    "trainer",
    "security",
    "inbound",
    "immediate",
    "finance",
    "recruiter",
    "cloud",
    "spring",
    "system",
    "integration",
    "intern"
]

SKILL_LIST = [
    "media planning",
    "digital media",
    "pre sales",
    "closing",
    "software knowledge",
    "clients",
    "requirements",
    "negotiating",
    "client",
    "online bidding",
    "good communication",
    "technology",
    "computer science",
    "fabrication",
    "quality check",
    "intellectual property",
    "electronics",
    "support services",
    "research",
    "management",
    "human resource management",
    "research executive",
    "technical support",
    "manual testing",
    "test engineering",
    "test cases",
    "web testing",
    "web technologies",
    "adobe experience manager",
    "digital",
    "digital marketing",
    "adobe analytics",
    "data analytics",
    "aem",
    "adobe",
    "sitecatalyst",
    "channel partners",
    "real estate",
    "negotiation",
    "property",
    "residential sales",
    "tfs",
    "azure",
    "git",
    "vsts",
    "docker",
    "dynatrace",
    "splunk",
    "aws",
    "bde",
    "technical support",
    "support services",
    "application support",
    "communication skills",
    "voice based process",
    "semi voice",
    "semi voice process",
    "secretary",
    "executive assistant",
    "ea",
    "website",
    "web analytics",
    "xml",
    "link building",
    "google analytics",
    "case studies",
    "seo",
    "social media",
    "tracking",
    "maintaining",
    "operations",
    "workflow",
    "tat",
    "monitoring",
    "mts",
    "email",
    "oracle idam|oim|oam",
    "digital marketing",
    "social media marketing",
    "content marketing",
    "email marketing",
    "sem",
    "campaign management",
    "facebook",
    "media management",
    "instrumentation engineering",
    "electrical engineering",
    "engineering",
    "fresher",
    "trainee",
    "immediate",
    "mechanical engineering",
    "electronics engineering",
    "undergraduate",
    "help desk",
    "customer service",
    "customer relationship",
    "access controls",
    "asset management",
    "vendor management",
    "report generation",
    "policies",
    "analytical",
    "procedures",
    "analysts",
    "data entry",
    "analytical skills",
    "copyright",
    "email",
    "jquery",
    "xml",
    "javascript",
    "cakephp",
    "customer service",
    "open source",
    "facebook",
    "css3",
    "c#",
    "ms dynamics crm",
    "microsoft dynamics",
    "ms dynamics",
    "sales manager",
    "business development manager",
    "relationship manager",
    "brokers",
    "insurance sales",
    "channel sales",
    "direct sale",
    "direct marketing",
    "sales",
    "marketing executive",
    "territory sales manager",
    "lead generation",
    "business development",
    "corporate sales",
    "contract management",
    "it services",
    "relationship building",
    "managed services",
    "selling",
    "market research",
    "qa executive",
    "java ee",
    "jms",
    "core java",
    "junit",
    "weblogic",
    "html",
    "jpa",
    "json",
    "soap",
    "sql",
    "conceptualization",
    "architecting",
    "continuous improvement",
    "side",
    "development",
    "front end",
    "it",
    "articulate storyline",
    "area sales management",
    "retail sales",
    "fmcg",
    "chocolate",
    "confectionary",
    "asm",
    "area sales manager",
    "area business manager",
    "java",
    "oop",
    "c++",
    "multithreading",
    "uml",
    "ooad",
    "oops",
    ".net",
    "debugging",
    "qmail",
    "nagios",
    "windows server",
    "networking",
    "mysql",
    "redhat",
    "centos",
    "java",
    "hibernate",
    "project management",
    "jdbc",
    "scrum master",
    "microservices",
    "agile",
    "rest",
    "vide",
    "java api",
    "banking",
    "j2ee",
    "api",
    "finance",
    "core java",
    "microservices",
    "gis",
    "iso 27001",
    "hr",
    "information system",
    "process",
    "iso 9001",
    "information security management",
    "gis software",
    "edge",
    "administration",
    "administrative support",
    "contract logistics",
    "staff development",
    "site management",
    "quality improvement",
    "warehousing",
    "warehouse operations",
    "filing",
    "tds",
    "service industry",
    "pf",
    "esi",
    "returns",
    "coaching",
    "payroll",
    "invoice",
    "tally",
    "outbound",
    "antivirus",
    "technical support",
    "sales",
    "spot",
    "inbound calls",
    "pay",
    "medical",
    "comp",
    "troubleshooting",
    "dns",
    "dhcp",
    "monitoring",
    "virtualization",
    "shell scripting",
    "python",
    "vms",
    "archiving",
    "4g",
    "3gpp",
    "3g",
    "system architect",
    "lte",
    "radio access network",
    "phd",
    "ieee",
    "arm processor",
    "device drivers",
    "embedded linux",
    "linux kernel",
    "ipc",
    "jms",
    "sonar",
    "j2ee",
    "svn",
    "spring",
    "oracle 11g",
    "market",
    "presentation",
    "strong analytical skills",
    "english",
    "presentation skills",
    "developing",
    "customer interaction",
    "fixed assets",
    "accounts payable",
    "record to report",
    "general accounting",
    "general ledger",
    "team management",
    "regional sales",
    "commercial activities",
    "commercial sales",
    "online sales",
    "senior management",
    "budgeting",
    "strategy implementation",
    "marketing",
    "e - commerce",
    "odi",
    "matrix",
    "javascript",
    "sql",
    "php",
    "php mysql",
    "css",
    "software development",
    "technical",
    "photoshop",
    "mca",
    "ajax",
    "jquery",
    "application",
    "web",
    "design",
    "html",
    "relationship management",
    "relationship building",
    "client relationship",
    "training",
    "analytical skills",
    "process mapping",
    "standard operating procedures",
    "visa processing",
    "android",
    "btech",
    "iphone",
    "server",
    "ios",
    "platforms",
    "objective c",
    "json",
    "programming",
    "c",
    "testing",
    "mobile",
    "xcode",
    "application development",
    "eclipse",
    "sdk",
    "applications",
    "cca",
    "bpo",
    "csr",
    "international bpo",
    "customer service",
    "outbound process",
    "customer care",
    "tourism",
    "customer support",
    "voice process",
    "inbound process",
    "cse",
    "bpo fresher",
    "voice support",
    "hotel",
    "travel",
    "bca",
    "graphics",
    "b tech",
    "core",
    "b sc",
    "b e",
    "publishing",
    "animation",
    "accounting",
    "continuous improvement",
    "process improvement",
    "load balancing",
    "lean six sigma",
    "black belt",
    "green belt",
    "process re - engineering",
    "process excellence",
    "business excellence",
    "otc",
    "networking",
    "information technology",
    "network administration",
    "technical support",
    "license management",
    "disaster recovery",
    "data security",
    "it training",
    "it software",
    "automobile",
    "digital content",
    "content development",
    "production",
    "web content writing",
    "tourism",
    "target achievement",
    "negotiation skills",
    "revenue management",
    "tour packages",
    "php",
    "networking",
    "data structures",
    "http",
    "software design",
    "computer science",
    "system design",
    "backend",
    "ticketing",
    "chief engineer",
    "hospitality",
    "hvac",
    "maintenance",
    "water treatment",
    "energy conservation",
    "capital expenditure",
    "weblogic",
    "configuration",
    "mysql",
    "installation",
    "oracle dba",
    "troubleshooting",
    "oracle rac",
    "service level",
    "data management",
    "hr coordinator",
    "management audit",
    "hr operations",
    "graphics",
    "windows os",
    "linux",
    "high performance computing",
    "test cases",
    "system software",
    "gaming",
    "freebsd",
    "sales",
    "team building",
    "strategic leadership",
    "real estate",
    "field sales",
    "sales strategy",
    "enterprise business",
    "go - to - market strategy",
    "enterprise sales",
    "sales executive activities",
    "facility management",
    "facility services",
    "sds",
    "radiology",
    "cpt",
    "icd - 10",
    "em",
    "medical coding",
    "coders",
    "surgery",
    "ed",
    "market analysis",
    "public relations",
    "cv",
    "market intelligence",
    "prospecting",
    "sales process",
    "branding",
    "erp",
    "mis",
    "succession planning",
    "reports",
    "talent management",
    "human resources",
    "hr policies",
    "recruitment",
    "talent acquisition",
    "revenue generation",
    "marketing",
    "ad sales",
    "co ordination",
    "team management",
    "drafting",
    "loans",
    "online",
    "coordination",
    "quality",
    "english",
    "php",
    "dom",
    "com",
    "web technologies",
    "written communication",
    "time",
    "cloud",
    "puppet",
    "python",
    "git",
    "kvm",
    "linux",
    "jenkins",
    "openstack",
    "ansible",
    "national",
    "branch",
    "vice president",
    "software",
    "mentor",
    "android",
    "consulting",
    "usage",
    "software",
    "coding",
    "backend",
    "investment",
    "performance testing",
    "software testing",
    "manual testing",
    "quality testing",
    "pivot table",
    "credit analysis",
    "tally erp",
    "accounting",
    "vlookup",
    "finance",
    "lookup",
    "advanced excel",
    "hlookup",
    "credit control",
    "international bpo",
    "kpo",
    "web chat",
    "non voice process",
    "e mail",
    "international call center",
    "customer service representative",
    "interpersonal skills",
    "ites",
    "uk shift",
    "e - commerce",
    "innovative",
    "aggressive",
    "communication skills",
    "detail engineering",
    "material handling",
    "autocad",
    "detailing",
    "design engineering",
    "microstation",
    "bid evaluation",
    "design",
    "android",
    "erp",
    "mvc",
    "technical writing",
    "technical documentation",
    "articles",
    "writing skills",
    "product support",
    "ansys",
    "thermal",
    "matlab",
    "mccb",
    "electricals",
    "product placement",
    "market research",
    "distributor handling",
    "business development executive",
    "customer service executive",
    "secondary sales",
    "supervision",
    "management accounting",
    "vat",
    "book keeping",
    "sage",
    "tax returns",
    "trade",
    "forex trading",
    "forex",
    "fx",
    "lead generation",
    "revenue generation",
    "current account",
    "xml",
    "tools",
    "joomla",
    "coding",
    "wordpress",
    "xhtml",
    "ajax",
    "zld",
    "engineering management",
    "knitting",
    "analyst",
    "erp",
    "change management",
    "business objects",
    "managed services",
    "business process mapping",
    "executive management",
    "data mining",
    "oracle project accounting",
    "testing",
    "intern",
    "windows",
    "unix",
    "perl",
    "iis",
    "redhat",
    "c",
    "woocommerce",
    "magento",
    "shopify",
    "jquery",
    "web development",
    "css",
    "singleton",
    "struts",
    "spring boot",
    "business development management",
    "bd",
    "projects",
    "bdm",
    "tendering",
    "proposal",
    "ethical hacking",
    "certified ethical hacker",
    "networking protocols",
    "penetration testing",
    "nessus",
    "nmap",
    "fortify",
    "vulnerability assessment",
    "appscan",
    "qualys",
    "graphic designing",
    "graphics",
    "adobe creative suite",
    "architecture",
    "ms office",
    "business executive",
    "payment collection",
    "costing",
    "lead generation",
    "vendor",
    "cost",
    "internship",
    "digital marketing",
    "social media",
    "animation",
    "creative",
    "indesign",
    "presentation skills",
    "senior",
    "market penetration",
    "marketing",
    "customer satisfaction",
    "enterprise business",
    "web technologies",
    "business development",
    "strategy",
    "aws",
    "sales",
    "jquery",
    "microsoft sql server",
    "net asp net",
    "ado.net",
    "microsoft",
    "unit tests",
    "database",
    ".net",
    "object oriented programming",
    "support",
    "technical recruitment",
    "us staffing",
    "us recruitment",
    "us recruiter",
    "us it staffing",
    "technical recruiter",
    "it recruiter",
    "recruiter",
    "w2",
    "c2c",
    "talent acquisition",
    "recruitment",
    "staffing",
    "sourcing",
    "front office executive",
    "project administration",
    "coordination",
    "order management system",
    "sterling commerce",
    "sterling",
    "oms",
    "sterling integrator",
    "ecommerce",
    "analytical",
    "documentation",
    "web development",
    "algorithms",
    "javascript",
    "sql server",
    "flex",
    "net",
    "nctvt",
    "drupal",
    "application programming",
    "team leader",
    "mvc",
    "zend",
    "software services",
    "project management",
    "analytical",
    "sales lead",
    "automation tools",
    "marketing automation",
    "autocad",
    "3d modeling",
    "fmea",
    "mechanical design",
    "solidworks",
    "automation engineer",
    "revenue cycle management",
    "us healthcare",
    "payment posting",
    "medical billing",
    "medical coding",
    "us visa",
    "team leading skills",
    "healthcare",
    "denial management",
    "rcm",
    "voice process",
    "qaqc",
    "writing",
    "process operations",
    "verbal",
    "patient care",
    "nursing",
    "people orientation",
    "report generation",
    "service quality",
    "disaster management",
    "customer care",
    "process orientation",
    "predictive modeling",
    "sas",
    "data management",
    "data mining",
    "tableau",
    "data analytics",
    "statistics",
    "analytics",
    "molecular biology",
    "chemistry",
    "biotechnology",
    "bhms",
    "biology",
    "physiotherapy",
    "microbiology",
    "nursing",
    "biomedical",
    "physics",
    "biochemistry",
    "pharmacy",
    "ophthalmology",
    "micro biology",
    "bioinformatics",
    "zoology",
    "biotech",
    "accounts executive",
    "accountant",
    "stock management",
    "gst",
    "auditing",
    "statutory compliance",
    "accounting",
    "account assistant",
    "bank reconciliation",
    "tax audit",
    "banking",
    "monthly reports",
    "payroll",
    "salary processing",
    "income tax",
    "income tax return",
    "taxation",
    "informatica power center",
    "informatica",
    "seo specialist",
    "advertising agency",
    "online marketing",
    "seo expert",
    "facebook marketing",
    "validation",
    "installation",
    "breakdown maintenance",
    "industrial safety",
    "gmp",
    "boiler",
    "design",
    "gensets",
    "air compressor",
    "breakdown",
    "ro",
    "who",
    "forecasting",
    "pay per click",
    "google adwords",
    "search engine marketing",
    "ppc",
    "sem",
    "google analytics",
    "website analysis",
    "yahoo",
    "web analytics",
    "marketing initiatives",
    "marketing officer",
    "pharma sales",
    "marketing representative",
    "marketing executive",
    "pharma marketing",
    "sales officer",
    "sales representative",
    "business development executive",
    "fresher",
    "trainee",
    "sales executive",
    "project management",
    "ppap",
    "automotive",
    "external audit",
    "conflict resolution",
    "resource mobilization",
    "pfmea",
    "risk management",
    "project life cycle",
    "pr",
    "public relations",
    "media relations",
    "social media",
    "marketing communication",
    "corporate communication",
    "media relation",
    "corp comm",
    "online media",
    "public relation",
    "journalism",
    "advertising",
    "mass communication",
    "counselling",
    "couselling",
    "student counsellor",
    "student counseling",
    "asp dot net",
    ".net developer",
    "dot net developer",
    "asp.net",
    "asp . net",
    "secondary research",
    "valuation",
    "primary",
    "report preparation",
    "business development",
    "due diligence",
    "financial modelling",
    "teaching",
    "educator",
    "counselor",
    "mentor",
    "trainer",
    "advisor",
    "x - ray",
    "medical transcription",
    "ultrasound",
    "ct scan",
    "cms",
    "wordpress",
    "drupal",
    "joomla",
    "cakephp",
    "zend",
    "knowledge",
    "xhtml",
    "sales management",
    "educational sales",
    "technical support associate",
    "us shift",
    "technical support",
    "english",
    "customer care executive",
    "issue",
    "c#",
    "application development",
    "senior level",
    "ms sql",
    "visual basic",
    "power bi",
    "msbi",
    "ssis",
    "recruitment",
    "data integration",
    "escalation management",
    "field sales executive",
    "sales achievement",
    "insurance sales",
    "salesforce",
    "skill development",
    "productivity improvement",
    "training management",
    "sales budgeting",
    "tsi",
    "networking",
    "scheduling",
    "publishing",
    "incident management",
    "vmware",
    "problem management",
    "remedy",
    "sip",
    "planning",
    "training",
    "training manager",
    "trainer",
    "faculty",
    "billing",
    "business reporting",
    "mis preparation",
    "corporate",
    "retail",
    "customer support",
    "support service",
    "field support",
    "team",
    "management",
    "supervisor",
    "self motivated",
    "continuous improvement",
    "give",
    "enthusiastic",
    "javascript",
    "application development",
    "solid",
    "data integrity",
    "stored procedures",
    "reporting tools",
    "senior design engineer",
    "engineering design",
    "sacs",
    "six sigma",
    "pmp",
    ".net",
    "javascript",
    "oracle",
    "assembly language",
    "real time operating systems",
    "technical support executive",
    "electrical engineering",
    "data analysis",
    "automation",
    "excel",
    "business intelligence",
    "product marketing",
    "data extraction",
    "detail design",
    "juniper",
    "smsc engineer",
    "routing",
    "ip networking",
    "network elements",
    "network troubleshooting",
    "high level design",
    "data center",
    "switching",
    "assistant restaurant manager",
    "restaurant",
    "restaurant manager",
    "layout",
    "visualization",
    "digital media",
    "graphic design",
    "illustration",
    "part time",
    "selling",
    "accounts",
    "events",
    "prospecting",
    "business operations",
    "ideas",
    "coordinating",
    "photoshop",
    "illustrator",
    "fireworks",
    "css3",
    "gui",
    "usability",
    "static",
    "photoshop",
    "bootstrap",
    "html5",
    "css",
    "python",
    "server",
    "multimedia",
    "audio",
    "user interface",
    "senior management",
    "mis reporting",
    "building",
    "risk",
    "focus",
    "trade",
    "associate vice president",
    "sales head",
    "tied channel",
    "business growth",
    "profitability",
    "business operations",
    "new business",
    "alliances",
    "project management",
    "qa",
    "life sciences",
    "development quality assurance",
    "life cycle",
    "regulatory affairs",
    "dqa",
    "qms",
    "dmf",
    "accounting",
    "financial reporting",
    "statutory compliance",
    "vat",
    "consumer research",
    "head business development",
    "testing",
    "quality",
    "etl",
    "bi",
    "dw",
    "datawarehouse testing",
    "assembly language",
    "c",
    "product management",
    "business process",
    "linkedin",
    "git",
    "technical",
    "sdlc",
    "ideas",
    "ajax",
    "website",
    "module",
    "customer service",
    "communication",
    "call center",
    "inbound",
    "voice",
    "non voice",
    "telecalling",
    "cro",
    "cce",
    "data entry",
    "back office",
    "domestic bpo",
    "telemarketing",
    "outbound",
    "hardware",
    "oracle",
    "core java",
    "business process",
    "outsourcing",
    "operations",
    "spring integration",
    "j2ee",
    "spring framework",
    "jee",
    "manager technology",
    "ms office",
    "data entry",
    "customer relationship",
    "automobile",
    "proposal preparation",
    "crm strategy",
    "database",
    "unix",
    "version control",
    "prototype",
    "merchandising",
    "buyer activities",
    "follow ups",
    "purchase",
    "vendor development",
    "powershell",
    "script writing",
    "debugging",
    "devops",
    "application integration",
    "computer operator",
    "comm",
    "typing speed",
    "who",
    "level",
    "operations management",
    "mobilization",
    "resource mobilization",
    "general management",
    "interview",
    "customer support executive",
    "staff training",
    "day care",
    "process",
    "night shift",
    "international bpo",
    "digital marketing",
    "email marketing",
    "adwords",
    "display advertising",
    "digital campaigns",
    "google analytics",
    "sem",
    "seo",
    "java",
    "cisco call manager",
    "visa",
    "sip",
    "offshore",
    "change management",
    "mobile",
    "mobiles",
    "handset",
    "mobile handset",
    "relationship management",
    "distribution management",
    "channel management",
    "dealer management",
    "retailer",
    "international call center",
    "technical support",
    "communication skills",
    "pc hardware",
    "technician activities",
    "analytical ability",
    "soft skills",
    "customer satisfaction",
    "illustrator",
    "corel draw",
    "photoshop",
    "manual testing",
    "process automation",
    "system testing",
    "pdf",
    "artificial intelligence",
    "regression testing",
    "silicon",
    "technical architecture",
    "fusion",
    "oracle fusion",
    "layout design",
    "web designing",
    "bpo voice",
    "voice process",
    "html5",
    "asp",
    "product training",
    "relationship",
    "customer profitability",
    "receivable management",
    "education",
    "transportation",
    "service",
    "key accounts",
    "stores",
    "warehouse",
    "logistics",
    "bpo",
    "troubleshooting",
    "linux",
    "fixed income",
    "machine learning",
    "asset management",
    "jira",
    "financial services",
    "admin executive",
    "stock inventory",
    "office management",
    "application",
    "credit officers",
    "risk management",
    "administration",
    "balance sheet finalisation",
    "service tax",
    "bank reconciliation",
    "financial auditing",
    "accounts payable",
    "ap",
    "change management",
    "analyst",
    "business analyst",
    "software development life cycle",
    "oee",
    "customer service representative",
    "security",
    "cctv",
    "laravel",
    "codeigniter",
    "telecom",
    "lan",
    "wan",
    "bss",
    "vpn",
    "wireless",
    "telecommunication",
    "visio",
    "business communication",
    "team management",
    "transition management",
    "trend analysis",
    "variance analysis",
    "usage",
    "cash handling",
    "merchandising",
    "salesforce",
    "salesforce.com",
    "system design",
    "application architecture",
    "execution",
    "project management",
    "ao engagement",
    "monitoring tools",
    "delivery management",
    "stakeholder management",
    "system monitoring",
    "recruitment",
    "hiring",
    "screening",
    "interviewing",
    "staffing",
    "cold calling",
    "bidding",
    "academic",
    "mba",
    "webservices",
    "system design",
    "esb",
    "debugging",
    "interpersonal skills",
    "programming",
    "developer",
    "direct sales",
    "cold calling",
    "business development manager",
    "customer interfacing",
    "data collection",
    "build automation",
    "entity framework",
    "recruitmentenglish",
    "domestic bpo",
    "hr",
    "human resource management",
    "placement coordination",
    "recruitment executive",
    "recruitment officer",
    "strategic sourcing",
    "procurement",
    "supply chain management",
    "packaging",
    "test engineering",
    "corporate training",
    "corporate trainer",
    "technical trainer",
    "mongodb",
    "spring",
    "jms",
    "procurement",
    "supply chain management",
    "copyright",
    "chain",
    "purchase",
    "head operations",
    "steel",
    "software development life cycle",
    "ui development",
    "design patterns",
    "svn",
    "software engineering",
    "angularjs",
    "good communication skill",
    "good speeking manners",
    "ability to face strangers",
    "punctual",
    "gopod efficiency",
    "e - tendering",
    "tender preparation",
    "bid preparation",
    "proposal preparation",
    "cash handling",
    "cashier activities",
    "day book",
    "cashier",
    "restaurant",
    "csat",
    "asp.net",
    "excel",
    "management trainee",
    "power point presentation",
    "eclipse",
    "scrum",
    "enterprise applications",
    "android sdk",
    "test driven development",
    "production management",
    "production control",
    "production planning",
    "production manager",
    "planning",
    "production support",
    "organizing",
    "project management",
    "management consulting",
    "business transformation",
    "strategy consulting",
    "change management",
    "sales strategy",
    "top management",
    "digital media",
    "bengali",
    "lms",
    "business administration",
    "content editor",
    "literature",
    "simulation",
    "power management",
    "hardware",
    "system analysis",
    "motion graphics",
    "infographics",
    "illustrator",
    "animations",
    "infographics",
    "corel draw",
    "coreldraw",
    "visual designer",
    "intranet",
    "tally",
    "accounts executive",
    "retail executive",
    "financial reporting",
    "due diligence",
    "data analysis",
    "international finance",
    "nse",
    "compliance",
    "equity",
    "client acquisition",
    "revenue generation",
    "hni client handling",
    "mysql",
    "technical writing",
    "cloud",
    "ui",
    "api",
    "architecture",
    "visual studio",
    "ms sql",
    "infrastructure",
    "agile",
    "aws",
    "mis reporting",
    "operational risk",
    "saving",
    "sales strategy",
    "sales management",
    "b2b sales",
    "institutional sales",
    "soa",
    "relationship management",
    "service oriented architectures",
    "quality systems",
    "software implementation",
    "computer science",
    "sql server 2008",
    "art director",
    "fresher",
    "icse",
    "outbound",
    "uk process",
    "bcom",
    "cbse",
    "chat process",
    "aviation",
    "guest relations",
    "public speaking",
    "pr",
    "warehouse",
    "manager operations",
    "telesales",
    "printers",
    "bonus",
    "single sign - on",
    "single sign on",
    "it infrastructure",
    "sso",
    "material selection",
    "ms",
    "mep",
    "corel draw",
    "co",
    "plumbing",
    "coding",
    "database design",
    "test cases",
    "analytical",
    "nosql",
    "cassandra",
    "accent",
    "soft skills",
    "training needs",
    "process compliance",
    "software development",
    "spring mvc",
    "ood",
    "jsf",
    "virtualization",
    "cloud computing",
    "server architecture",
    "windows troubleshooting",
    "customer satisfaction",
    "manager technology",
    "deployment",
    "business development",
    "sales marketing",
    "sales manager",
    "area sales manager",
    "territory sales manager",
    "territory manager",
    "area manager",
    "regional manager",
    "regional sales manager",
    "regional business manager",
    "sale",
    "networking sales",
    "it solution sales",
    "structured cabling",
    "passive networking",
    "data center",
    "cable tray",
    "cabling",
    "data center rack",
    "data - centre rack",
    "utp cables",
    "marketing executive",
    "distributors",
    "customer profiling",
    "fundraising",
    "worldspan",
    "travel sales consultants",
    "galileo",
    "amadeus",
    "gds",
    "front end",
    "min",
    "ui",
    "phone",
    "strategic hr",
    "doc",
    "consultancy",
    "cvs",
    "middle east",
    "customization",
    "e-commerce",
    "crm",
    "open",
    "java",
    "angular js",
    "hibernate",
    "core java",
    "technical leader",
    "technical",
    "javascript",
    "spring",
    "jquery",
    "js framework",
    "senior management",
    "ngo",
    "key skills",
    "corporate social responsibility",
    "govt liasioning",
    "corporate pr",
    "external communications",
    "asp.net mvc",
    "entity framework",
    "loans",
    "direct sales associate",
    "bfsi",
    "sanction",
    "monitoring",
    "senior resident",
    "ram",
    "dnb",
    "dmc",
    "angularjs",
    "responsive web design",
    "bootstrap",
    "grunt",
    "python",
    "open source",
    "java",
    "perl",
    "nosql",
    "functional testing",
    "sales engineering",
    "design development"
    "software engineering",
    "lighting",
    "computer science",
    "product quality",
    "automation testing",
    "asset management",
    "gui",
    "object oriented programming",
    "android",
    "nav calculation",
    "fund accounting",
    "corporate actions",
    "process improvement",
    "reconciliation",
    "subject matter expert",
    "secondary research",
    "network security",
    "ips",
    "advisory",
    "firewall",
    "team management",
    "training need analysis",
    "sales training",
    "product training",
    "skill development",
    "retail marketing",
    "regional management",
    "competency mapping",
    "training delivery",
    "hiring",
    "hris",
    "pharmaceutical",
    "medical",
    "pharma",
    "medical billing",
    "healthcare",
    "seo",
    "hosting",
    "mechanical operation",
    "preventive maintenance",
    "mechanical",
    "engineeringbreak down maintenance",
    "mechanical maintenance",
    "smarty",
    "third party",
    "software development life cycle",
    "renewable energy",
    "power distribution",
    "power sector",
    "banking",
    "electricals",
    "spanish language expert",
    "chinese",
    "spanish",
    "sales associate",
    "voice process",
    "mcse",
    "support engineer",
    "ssrs",
    "sql server",
    "stored procedures",
    "sql development",
    "git",
    "machine learning",
    "gnm",
    "institutions",
    "relationships",
    "customer",
    "customers",
    "implementation",
    "company",
    "site",
    "product",
    "recruitment",
    "volume hiring",
    "hr",
    "bpo hiring",
    "sourcing",
    "interviewing",
    "onboarding",
    "staffing",
    "orientation",
    "human resource management",
    "web services",
    "financial analysis",
    "financial planning",
    "vp finance",
    "publishing",
    "content management",
    "management systems",
    "brand awareness",
    "auditing",
    "audit planning",
    "risk assessment",
    "credit risk",
    "credit policy",
    "c++",
    "gaming",
    "opengl",
    "sales associate",
    "field sales",
    "mba fresher",
    "new product development",
    "rest",
    "oop",
    "oracle",
    "visualization",
    "commerce",
    "process automation",
    "commodity markets",
    "operations",
    "robotics",
    "it sales",
    "marketing campaigns",
    "btl",
    "marketing management",
    "digital marketing",
    "dealer sales",
    "channel partners",
    "process flow",
    "android",
    "middleware",
    "firmware",
    "soc",
    "linux kernel",
    "bluetooth",
    "test scripts",
    "test strategy",
    "technical support executive",
    "inbound voice process",
    "sales executive",
    "recruitment executive",
    "ir",
    "web development",
    "inside sales",
    "cloud",
    "advisory services",
    "general insurance",
    "sales initiatives",
    "financial products",
    "distributor sales",
    "branch sales",
    "sales development",
    "motor insurance",
    "clinical pharmacy",
    "mr",
    "territory executive",
    "sap",
    "scm",
    "material",
    "sheetmetal",
    "sheet metal",
    "vd",
    "bop",
    "computer science",
    "data analysis",
    "admissions",
    "placements",
    "help desk",
    "academic research",
    "ifrs",
    "us gaap",
    "international taxation",
    "cost accounting",
    "company secretary",
    "company law",
    "corporate law",
    "icwa",
    "cma",
    "marketing",
    "it sales",
    "ncr",
    "hardware sales",
    "group",
    "rt",
    "pt",
    "mpi",
    "ndt inspection",
    "ndt level",
    "diploma",
    "quality inspection",
    "level ii",
    "inspection engineering",
    "ut",
    "customer service",
    "customer relationship",
    "graphic designing",
    "cad",
    "application software",
    "any graduate",
    "voice support",
    "technical sales associate",
    "technical associate",
    "voice support",
    "equipment maintenance",
    "hydraulics",
    "inventory management",
    "management skills",
    "maintenance head",
    "hive",
    "apache",
    "itil process",
    "hadoop",
    "big data",
    "motor insurance",
    "insurance broking",
    "general insurance",
    "sql",
    "hibernate",
    "multithreading",
    "ooad",
    "eclipse",
    "business process",
    "outsourcing",
    "version control",
    "memory management",
    "control system",
    "catia",
    "pressure vessels",
    "mechanical",
    "primavera",
    "pscad",
    "project execution",
    "program management",
    "customer experience",
    "supply chain",
    "operations planning",
    "business development management",
    "sales management",
    "outbound sales",
    "tele sales",
    "operations",
    "bhm",
    "front office",
    "hospitality management",
    "hotel management",
    "financial s",
    "windows",
    "mobile development",
    "hardware board design",
    "mixed signal",
    "environment",
    "functional",
    "operations",
    "business",
    "verbal communication",
    "screening",
    "it recruitment",
    "hr recruitment",
    "sourcing",
    "eclipse ide",
    "retail sales",
    "inhouse sales",
    "customer support",
    "international voice",
    "international voice process",
    "j2ee",
    "tomcat",
    "selenium",
    "ofbiz",
    "android development",
    "android studio",
    "api testing",
    "counselor",
    "teaching",
    "branding",
    "competitive intelligence",
    "market analysis",
    "wireless",
    "aerospace",
    "fpga",
    "system verilog",
    "physical design",
    "hr",
    "hiring",
    "head hunting",
    "leadership",
    "mass hiring",
    "volume hiring",
    "bulk hiring",
    "team leader",
    "senior",
    "tl",
    "non it",
    "it recruitment",
    "technical hiring",
    "bfsi",
    "engineering",
    "manufacturing",
    "insurance",
    "it",
    "associate",
    "receptionist",
    "front desk",
    "travel arrangements",
    "computer operating",
    "soa",
    "proactive",
    "asp net c",
    "qms",
    "impex",
    "environmental management system",
    "warehouse management system",
    "export import logistics",
    "j2ee",
    "ldap",
    "adfs",
    "json",
    "rest",
    "java web services",
    "java api",
    "advanced java",
    "open source",
    "soa",
    "spring integration",
    "spring boot",
    "spring security",
    "spring mvc",
    "dynamics crm",
    "solution management",
    "root cause",
    ".net development",
    "marketing strategy",
    "strategic thinking",
    "interpersonal communication",
    "promotions",
    "account management",
    "team leading",
    "business development management",
    "o2c",
    "otc",
    "order management",
    "credit management",
    "communication skills",
    "visualization",
    "m e p",
    "modeling",
    "design development",
    "drawings",
    "cad",
    "preparation",
    "pnr",
    "primetime",
    "sta",
    "floorplan",
    "timing closure",
    "synthesis",
    "vlsi",
    "floor planning",
    "assistant manager purchase",
    "sql",
    "solution architecture",
    "scala",
    "cosmos",
    "data warehousing",
    "transactional quality",
    "quality management",
    "quality manager",
    "manager quality",
    "iis",
    "exchange server",
    "windows server",
    "wss",
    "sharepoint",
    "active directory",
    "pharma chemicals",
    "intermediates",
    "hibernate",
    "design patterns",
    "exadata",
    "performance tuning",
    "11g",
    "patching",
    "dataguard",
    "rac",
    "cassandra",
    "oracle database",
    "ebs",
    "asm",
    "apps dba",
    "cloning",
    "hospital",
    "pharma",
    "agency sales",
    "direct sales",
    "life advisor",
    "life insurance advisor",
    "life insurance",
    "agency",
    "training needs",
    "accent",
    "feedback",
    "coaching",
    "process compliance",
    "real estate construction",
    "project manager",
    "project coordinator",
    "site coordinator",
    "multimedia",
    "adobe after effects",
    "protools",
    "graphic designing",
    "english language",
    "chat process",
    "tele caller",
    "process developer",
    "b.a",
    "exl",
    "ba",
    "blended process",
    "bba",
    "wipro",
    "tcs",
    "bbm",
    "accenture",
    "wns",
    "project support",
    "maya",
    "it asset",
    "hardware troubleshooting",
    "it services",
    "data services",
    "master data management",
    "fine arts",
    "user interface designing",
    "game development",
    "creative content",
    "relationship executive",
    "project management",
    "project planning",
    "leadership training",
    "apache camel",
    "activemq",
    "customer profiling",
    "customer segmentation",
    "brand management",
    "strategic partnerships",
    "brand marketing",
    "consumer insights",
    "performance appraisal",
    "promotional strategies",
    "marketing strategy",
    "negotiation",
    "marine operation",
    "manufacturing",
    "inventory",
    "fire safety",
    "fire",
    "data science",
    "installation",
    "breakdown maintenance",
    "preventive maintenance",
    "dot matrix",
    "printer",
    "printer support",
    "laserjet",
    "reporting",
    "data analysis",
    "business analytics",
    "html",
    "rest",
    "web services",
    "us it recruiter",
    "us it recruitment",
    "us technical recruiter",
    "service engineering",
    "maintenance",
    "breakdown",
    "shutdown",
    "amc",
    "repair",
    "field service engineer",
    "preventive maintenance",
    "breakdown maintenance",
    "field engineer",
    "electrical engineer",
    "enterprise sales",
    "new business",
    "marketing management",
    "cross selling",
    "product marketing",
    "consultative sales",
    "b2b marketing",
    "service sales",
    "corporate sales",
    "key accounts manager",
    "inbound",
    "costing",
    "good communication skills",
    "tickets",
    "tour",
    "experience",
    "manager",
    "packages",
    "monthly reports",
    "water quality",
    "kaggle",
    "nlp",
    "data science",
    "artificial intelligence",
    "natural language processing",
    "analytical techniques",
    "text mining",
    "big data",
    "machine learning",
    "deep learning",
    "talent acquisition",
    "campus hiring",
    "recruiting",
    "project sales",
    "architects",
    "sales operations",
    "distributor",
    "interior designers",
    "area management",
    "contractors",
    "area",
    "developers",
    "consultants",
    "dealer",
    "territory management",
    "sales manager",
    "retail",
    "sme",
    "manager sales",
    "assistant sales manager",
    "mice",
    "travel agent",
    "senior sales executive",
    "senior sales officer",
    "hotel sales",
    "room sales",
    "sales executive",
    "vba",
    "macros",
    "advanced excel",
    "oracle sql",
    "business analysis",
    "data mining",
    "business analyst",
    "asp net",
    "web application",
    "ms sql server",
    "asp.net mvc",
    "land acquisition",
    "unix",
    "db2",
    "flex",
    "pl",
    "cnc",
    "cnc operator",
    "cnc maintenance",
    "cnc programming",
    "medical representative",
    "senior executive",
    "sales engineer",
    "solution architect",
    "presales",
    "solution consultant",
    "technology consultant",
    "inside sales",
    "cold calling",
    "proposal writing",
    "convincing power",
    "customer care",
    "inbound process",
    "night shift",
    "customer care officer",
    "bpo",
    "performance management",
    "design development",
    "conceptualization",
    "sales support",
    "service delivery",
    "enterprise mobility",
    "tools",
    "laundry",
    "tds",
    "financial statements",
    "invoice processing",
    "business opportunity",
    "accounts receivable",
    "t-sql",
    "data manipulation",
    "system analyst",
    "scripting",
    "audit",
    "credit officers",
    "internal audit",
    "tax",
    "accounts",
    "gsm",
    "ethernet",
    "optimization",
    "product development",
    "gps",
    "lcd",
    "embedded",
    "spi",
    "fortigate",
    "routing",
    "hyper - v",
    "dlp",
    "sophos",
    "switching",
    "sqlite",
    "hvac",
    "instrumentation",
    "autodesk",
    "food processing",
    "project delivery",
    "electronic trading",
    "structured finance",
    "dcf",
    "equity research",
    "bloomberg",
    "investment banking",
    "bonds",
    "valuation",
    "hedge fund",
    "financial modelling",
    "structured products",
    "fixed income",
    "product management",
    "analytical skills",
    "software architecture",
    "prototype",
    "business analysis",
    "manager technology",
    "outsourcing",
    "resource management",
    "operations",
    "solution architecting",
    "office automation",
    "residential sales",
    "sales strategy",
    "real estate sales",
    "executive search",
    "biotechnology",
    "medical coder",
    "life sciences",
    "com",
    "application support",
    "sap is-utilities",
    "change",
    "entry level",
    "network",
    "rf",
    "action plan",
    "software sales",
    "business planning",
    "rfq",
    "rfp",
    "equity",
    "currency",
    "mutual funds",
    "commodities",
    "stock broking",
    "new client acquisition",
    "business generation",
    "channel distribution",
    "team management",
    "team handling",
    "weld shop",
    "press shop",
    "pressing",
    "salesforce developer",
    "sfdc developer",
    "twitter",
    "internet",
    "search engine optimisation",
    "head hunting",
    "screening",
    "technical recruitment",
    "recruitment consultant",
    "excel powerpoint",
    "sap plm",
    "sap mm",
    "sap ehs",
    "microstrategy",
    "business intelligence",
    "cognos",
    "business objects",
    "marketing",
    "event management",
    "brand management",
    "asp.net",
    "supply chain",
    "dbmstools",
    "metadata",
    "san",
    "veritas",
    "netbackup",
    "webex",
    "unix operating system",
    "tcp/ip",
    "it infrastructure",
    "procurement",
    "django",
    "presales",
    "real estate sales",
    "b2b sales",
    "kam",
    "commercial vehicle",
    "enterprises sales",
    "editing",
    "proof reading",
    "content writer",
    "editor",
    "article writing",
    "mass communication",
    "copywriter",
    "associate editor",
    "sub editor",
    "english writing",
    "set",
    "eee",
    "cms",
    "mbbs",
    "b.sc",
    "biotech",
    "dermatology",
    "rheumatology",
    "ent",
    "bds",
    "medicine",
    "pathology",
    "immunology",
    "radiology",
    "genetics",
    "bams",
    "mds",
    "gdb",
    "data quality",
    "nursing",
    "nicu",
    "medical",
    "patient care",
    "nurse",
    "back office processing",
    "computer operator",
    "account",
    "shares",
    "nosql",
    "r",
    "scala",
    "data visualization",
    "data science",
    "data modeling",
    "algorithm",
    "it helpdesk",
    "freshers",
    "international voice",
    "technical helpdesk",
    "service desk",
    "uk",
    "us",
    "jquery",
    "business development",
    "bde",
    "senior business analyst",
    "banker",
    "private banker",
    "sales officer",
    "sales engineer",
    "technical sales",
    "interpersonal skills",
    "direct marketing",
    "it hardware",
    "support executive",
    "analytical skills",
    "educational qualification",
    "stores",
    "forecasting",
    "cables",
    "organization skills",
    "product management",
    "product pricing",
    "user experience",
    "marketting",
    "tsm",
    "draughtsman",
    "civil",
    "3d",
    "tdd",
    "saas",
    "data structure",
    "mba finance",
    "auditing",
    "internal audit",
    "sox",
    "audit compliance",
    "technical management",
    "agile methodology",
    "unit testing",
    "design development",
    "big data",
    "sql queries",
    "spark",
    "performance tuning",
    "test case design",
    "html5",
    "node.js",
    "core php",
    "design studio",
    "strategy consulting",
    "big data analytics",
    "qlikview",
    "tea",
    "coffee",
    "office assistance",
    "admin",
    "office assistant",
    "oracle database",
    "vb.net",
    "sql server 2008",
    "ms.net",
    "deployment",
    "specification",
    "vb",
    "plsql",
    "pl",
    "wip",
    "hr policies",
    "stakeholder management",
    "business solutions",
    "green field projects",
    "gap analysis",
    "regulatory compliance",
    "account mining",
    "delivery lead",
    "oracle retail",
    "accounting entries",
    "debit",
    "document verification",
    "problem solving",
    "open office",
    "dispute management",
    "sql server 2008",
    "problem",
    "java",
    "business analysts",
    "lead developers",
    "ios development",
    "architect",
    "epc",
    "access controls",
    "technology",
    "intellectual property",
    "oracle sales",
    "microsoft dynamics ax",
    "strategy implementation",
    "proposal development",
    "resource planning",
    "cost management",
    "enterprise applications",
    "microsoft applications",
    "process design",
    "technical consultant",
    "international sales",
    "international marketing",
    "international business development",
    "export marketing",
    "teradata",
    "iphone",
]

SCHOOL_DICT = {
    "Adrian College":31,
    "Albion College":20,
    "Alma College":29,
    "Andrews University":15,
    "Aquinas College":30,
    "Baker College":25,
    "Calvin University":7,
    "Central Michigan University":9,
    "Cleary University":41,
    "College for Creative Studies":33,
    "Concordia University Ann Arbor":40,
    "Cornerstone University":27,
    "Cranbrook Academy of Art":35,
    "Davenport University":28,
    "Eastern Michigan University":12,
    "Ferris State University":10,
    "Finlandia University":37,
    "Grace Christian University":43,
    "Grand Valley State University":6,
    "Great Lakes Christian College":45,
    "Hillsdale College":11,
    "Hope College":14,
    "Kalamazoo College":21,
    "Kettering University":18,
    "Kuyper College":44,
    "Lake Superior State University":19,
    "Lawrence Technological University":24,
    "Madonna University":34,
    "Michigan School of Psychology":46,
    "Michigan State University":2,
    "Michigan Technological University":4,
    "Northern Michigan University":13,
    "Northwood University":26,
    "Oakland University":8,
    "Rochester University":42,
    "Saginaw Valley State University":22,
    "Siena Heights University":39,
    "Spring Arbor University":32,
    "The University of Olivet":38,
    "University of Detroit Mercy":17,
    "University of Michigan":1,
    "University of Michigan-Dearborn":16,
    "University of Michigan-Flint":23,
    "Walsh College":36,
    "Wayne State University":3,
    "Western Michigan University":5
}